### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by FelipeMarani** [TCC-INF2CM/MarketplaceProdutosNaturais#1]
![imagem_2023-02-27_162209841](https://user-images.githubusercontent.com/97049270/221662162-1b70b8cd-c944-49c6-8bf6-1de34276dc54.png)

Porque do footer rosa no final da página?

**Comment by Diego0668** [comment]
mano eu tava usando só de exemplo sabe? mas a ideia é ser da cor que estavamos planejando que é o verde mas eu não tava conseguindo mexer em nada nesse rodapé

**Comment by FelipeMarani** [comment]
ok
